(() => {
 installCalendarScenes();

 const widget=document.getElementById('fb-widget-1'),status=document.getElementById('calendar-status'),loading=document.getElementById('calendar-loading'),error=document.getElementById('calendar-error');
 let timer,scheduled=false;
 function showError(){loading.hidden=true;error.hidden=false;status.textContent='Connexion nécessaire';status.classList.remove('ready');}
 function refresh(){scheduled=false;if(!navigator.onLine||!widget.querySelector('.fbw-calendar--day'))return;loading.hidden=true;error.hidden=true;clearTimeout(timer);status.textContent='Disponibilités en direct';status.classList.add('ready');widget.querySelectorAll('.fbw-calendar--button').forEach((b,i)=>b.setAttribute('aria-label',i===0?'Mois précédent':'Mois suivant'));widget.querySelectorAll('.fbw-calendar--day').forEach(day=>{const selectable=day.classList.contains('valid_day')&&!day.classList.contains('unavailable_day')&&!day.classList.contains('unclickable_day'),number=day.querySelector('.day--number')?.textContent.trim()||'';if(!number)return;const month=day.closest('.fbw-calendar--month-bloc')?.querySelector('.fbw-calendar--month-name')?.textContent.trim()||'',price=day.querySelector('.day--price')?.textContent.trim()||'';day.setAttribute('role','button');day.tabIndex=selectable?0:-1;day.setAttribute('aria-disabled',String(!selectable));day.setAttribute('aria-pressed',String(day.classList.contains('chosen_day')));day.setAttribute('aria-label',`${number} ${month}${price?', '+price:''}${selectable?'':', non réservable'}`);});widget.querySelectorAll('.next--button').forEach(b=>{b.setAttribute('role','button');b.tabIndex=0;b.setAttribute('aria-label','Continuer la réservation sur D-EDGE');});const dates=widget.querySelector('.fbw-calendar--dates'),arrival=dates?.querySelector('.date--arrival .value')?.textContent.trim(),departure=dates?.querySelector('.date--departure .value')?.textContent.trim();const step=document.getElementById('calendar-step');step.textContent=arrival?(departure?`${arrival} → ${departure}`:`Arrivée : ${arrival} · choisissez le départ.`):'Choisissez votre arrivée, puis votre départ.';}
 new MutationObserver(()=>{if(!scheduled){scheduled=true;requestAnimationFrame(refresh);}}).observe(widget,{childList:true,subtree:true,characterData:true});
 widget.addEventListener('keydown',e=>{const t=e.target.closest('[role="button"]');if(t&&t.getAttribute('aria-disabled')!=='true'&&['Enter',' '].includes(e.key)){e.preventDefault();t.click();}});
 if(navigator.onLine){const script=document.createElement('script');script.src='https://websdk.d-edge.com/widgets/app.js';script.async=true;script.onerror=showError;document.body.appendChild(script);timer=setTimeout(showError,22000);}else{widget.hidden=true;showError();}
 window.addEventListener('offline',()=>{widget.hidden=true;showError();});document.getElementById('retry-calendar').addEventListener('click',()=>location.reload());
})();
